version: '3.8'

services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./models:/code/models
      - ./data:/code/data
    environment:
      - MODEL_PATH=/code/models/artifacts/model.pth
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    depends_on:
      - mlflow

  mlflow:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5000:5000"
    volumes:
      - ./mlruns:/code/mlruns
      - ./data:/code/data
    command: ["mlflow", "server", "--host", "0.0.0.0"]

  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
      - "5000:5000"
    volumes:
      - .:/code
      - ./models:/code/models
      - ./data:/code/data
    environment:
      - PYTHONPATH=/code/src:$PYTHONPATH
      - MODEL_PATH=/code/models/artifacts/model.pth
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    command: ["uvicorn", "src.api.main:app", "--host", "0.0.0.0", "--port", "8080", "--reload"]
    depends_on:
      - mlflow
